### ISSUE TITLE
Use consistent way to refer to "the minor" or "the child"

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-CLAGuardianship#11]
Need to decide between 2 options:

* Reasons to say "the child": it's a simple plain language term.
* Reasons to say "the minor": it may be more inclusive for children between 14-18

In many cases, we can use the name instead (#5)

See also #5 and also #84

**Comment by RamiLorca** [comment]
We decided to go with "the minor".
