### ISSUE TITLE
Are you the attorney? | While it does say attorney at the bottom of the form, I believe a pro se party is still required to fill out the signature block a the petitioner.

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-CLAGuardianship#65]

**Comment by RamiLorca** [comment]
@nonprofittechy So if a client is filling out this form without the help of an attorney, would the signature blocks end up looking like the image below?

<img width="682" alt="Pro se petitioner signature" src="https://github.com/user-attachments/assets/3cad93d2-ad40-4d61-9691-3ec3739d6832">

**Comment by nonprofittechy** [comment]
If this is all just one form, no, it looks like the petitioner and attorney sign in different places

**Comment by nonprofittechy** [comment]
After looking at the code, we think this feedback is invalid -- maybe an older version of the link?
