### ISSUE TITLE
Removal of Guardian - Make sure correct people appearing in Military Affidavit

### ISSUE THREAD

**Issue by RamiLorca** [LemmaLegalConsulting/docassemble-CLAGuardianship#85]
Currently, the Military Affidavit appears to leave out some of the people that have been previously named in the interview. Issue is likely related to the additional_parties list in customized_screens.yml.

**Comment by nonprofittechy** [comment]
I checked and this was customized in `customized_screens.yml`, but that file isn't mentioned in the petition_for_removal.yml.

Looking over the other stuff in customized_screens.yml, I think that's correct--the customized_screens.yml is only useful for the petition for appointment. I realize the name could be better for that! This repo is a little unusual in having at least 4 different paths that can each be executed separately.
