### ISSUE TITLE
Removal of Guardian - Hide nav sections when user is minor

### ISSUE THREAD

**Issue by RamiLorca** [LemmaLegalConsulting/docassemble-CLAGuardianship#86]
When user is minor, certain nav sections need to be hidden (e.g. Fe Waiver). Current code that attempts to do this is not working.

**Comment by nonprofittechy** [comment]
The logic in the al_nav_sections looks correct, but this code block was missing:

```yaml
---
code: |
  enable_al_nav_sections = True
```

See: https://assemblyline.suffolklitlab.org/docs/framework/navigation#turning-on-the-assembly-line-navigation-system

**Comment by nonprofittechy** [comment]
One other issue: it uses `data` rather than `data from code`. When you use `data`, the conditions (what makes `hidden` applicable) need to be in `mako` tags, like `${ showifdef("...") }`
